[package]
name = "encrypted-dns"
version = "0.2.9"
authors = ["Frank Denis <github@pureftpd.org>"]
edition = "2018"
description = "A modern encrypted DNS server (DNSCrypt v2, Anonymized DNSCrypt, DoH)"
keywords = ["dnscrypt", "encryption", "dns", "doh", "proxy"]
license = "MIT"
homepage = "https://github.com/jedisct1/encrypted-dns-server"
repository = "https://github.com/jedisct1/encrypted-dns-server"
categories = ["asynchronous", "network-programming","command-line-utilities"]
readme = "README.md"

[dependencies]
byteorder = "1.3.2"
clap = { version="2.33.0", default-features = false, features=["wrap_help", "nightly"] }
clockpro-cache = "0.1.8"
coarsetime = "0.1.11"
daemonize-simple = "0.1.2"
derivative = "1.0.3"
dnsstamps = "0.1.1"
env_logger = { version="0.7.0", default-features = false, features = ["humantime"]}
failure = "0.1.5"
futures-preview = { version = "=0.3.0-alpha.19", features = ["async-await", "unstable", "cfg-target-has-atomic"] }
jemallocator = "0.3.2"
libsodium-sys-stable="1.18.1"
log = { version = "0.4.8", features = ["std", "release_max_level_debug"] }
net2 = "0.2.33"
parking_lot = "0.9.0"
privdrop = "0.3.3"
rand = "0.7.2"
serde = "1.0.101"
serde_derive = "1.0.101"
serde-big-array = "0.2.0"
siphasher = "0.3.1"
tokio = "=0.2.0-alpha.6"
tokio-net = "=0.2.0-alpha.6"
toml = "0.5.3"

[dependencies.hyper]
optional = true
version = "0.13.0-alpha.4"
default_features = false

[dependencies.prometheus]
optional = true
version = "0.7.0"
default_features = false
features = ["process"]

[features]
default = ["metrics"]
metrics = ["hyper", "prometheus"]

[profile.release]
codegen-units = 1
incremental = false
panic = "abort"
