[package]
name = "encrypted-dns"
version = "0.1.1"
authors = ["Frank Denis <github@pureftpd.org>"]
edition = "2018"
description = "A modern encrypted DNS server (DNSCrypt, Anonymized DNSCrypt, DoH)"
keywords = ["dnscrypt", "encryption", "dns", "doh", "proxy"]
license = "MIT"
homepage = "https://github.com/jedisct1/encrypted-dns-server"
repository = "https://github.com/jedisct1/encrypted-dns-server"
categories = ["asynchronous", "network-programming","command-line-utilities"]
readme = "README.md"

[dependencies]
byteorder = "1.3.2"
clap = { version="2.33.0", features=["wrap_help", "nightly"] }
clockpro-cache = "0.1.8"
coarsetime = "0.1.11"
derivative = "1.0.3"
dnsstamps = "0.1.1"
env_logger = "0.6.2"
failure = "0.1.5"
futures-preview = { version = "=0.3.0-alpha.18", features = ["async-await", "nightly", "cfg-target-has-atomic"] }
jemallocator = "0.3.2"
libsodium-sys-stable="0.0.18"
log = "0.4.8"
net2 = "0.2.33"
parking_lot = "0.9.0"
privdrop = "0.3.3"
rand = "0.7.2"
serde = "1.0.101"
serde_derive = "1.0.101"
serde-big-array = "0.1.5"
siphasher = "0.3.1"
tokio = "=0.2.0-alpha.4"
tokio-net = "=0.2.0-alpha.4"
toml = "0.5.3"

[profile.release]
lto = true
panic = "abort"
opt-level = 3
