name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: hecrj/setup-rust-action@master
        with:
          rust-version: nightly
      - name: Check Cargo availability
        run: cargo --version
      - name: Check Rustup default toolchain
        run: rustup default | grep nightly
      - name: Build
        run: |
          env RUSTFLAGS="-C link-arg=-s" cargo build --release
          mkdir encrypted-dns
          mv target/release/encrypted-dns encrypted-dns/
          cp README.md encrypted-dns.toml encrypted-dns/
      - uses: actions/upload-artifact@master
        with:
          name: encrypted-dns-linux-x86_64
          path: encrypted-dns
